status = [
  "FreeBSD",
  "Lint",
  "Linux container:ruby:2.4-alpine",
  "Linux container:ruby:2.5-alpine",
  "Linux container:ruby:2.6-alpine",
  "Windows RUBY_VERSION:2.5.3.101",
  "Windows RUBY_VERSION:2.6.3.1",
  "macOS RUBY_VERSION:2.5",
  "macOS RUBY_VERSION:2.6",
  #"continuous-integration/travis-ci/push",
  #"continuous-integration/appveyor/branch"
]

# Uncomment this to use a two hour timeout.
# The default is one hour.
#timeout_sec = 7200
